confirmonquit: false
gui:
  mouseevents: false
  scrollheight: 2
  sidepanelwidth: 0.3333
  theme:
    activebordercolor:
    - green
    - bold
    inactivebordercolor:
    - white
    lighttheme: false
    optionstextcolor:
    - blue
    selectedlinebgcolor:
    - blue
keybinding:
  dependencies:
    changetype: t
  main:
    toggledragselect: v
    toggledragselect-alt: V
  packages:
    build: b
    globallink: L
    link: l
    pack: p
    publish: P
  status:
    checkforupdate: h
  universal:
    cleaninstall: I
    edit: o
    executecustomcommand: ':'
    gointo: <enter>
    gotobottom: '>'
    gototop: <
    install: l
    kill: z
    new: k
    nextblock: <right>
    nextblock-alt: i
    nextitem: <down>
    nextitem-alt: e
    nextmatch: =
    nextpage: .
    nextscreenmode: +
    nexttab: ']'
    openfile: O
    optionmenu: x
    optionmenu-alt1: '?'
    prevblock: <left>
    prevblock-alt: "n"
    previtem: <up>
    previtem-alt: u
    prevmatch: '-'
    prevpage: ','
    prevscreenmode: _
    prevtab: '['
    quit: q
    quit-alt1: <c-c>
    quitwithoutchangingdirectory: Q
    redo: <c-r>
    refresh: R
    remove: d
    return: <esc>
    scrolldownmain: <pgdown>
    scrolldownmain-alt1: E
    scrolldownmain-alt2: <c-d>
    scrollupmain: <pgup>
    scrollupmain-alt1: U
    scrollupmain-alt2: <c-u>
    select: <space>
    startsearch: /
    togglepanel: <tab>
    update: h
reporting: "off"
splashupdatesindex: 0
startuppopupversion: 1
update:
  days: 14
  method: prompt
